### ISSUE TITLE
Arbiter Pool Dashboard

### ISSUE THREAD

**Issue by kmw101** [confio/tgrade-app#260]
As an arbiter pool member I have a view on the open proposals and a button to create a proposal.

https://www.figma.com/file/8PU2KrQ9J3lnzcFysQ3pc7/desktop-light?node-id=5172%3A3415

--------

- [x] [Arbiter Pool - adjust utils for 'Voting rules'](https://github.com/confio/tgrade-app/issues/646)
- [x] [Arbiter Pool - fetch voters (Members)](https://github.com/confio/tgrade-app/issues/645)
- [x] [Open Text Proposal in Arbiter Pool](https://github.com/confio/tgrade-app/issues/456)
- [ ] [Create a Dispute Proposal : Frontend flow](https://github.com/confio/tgrade-app/issues/261)
- [ ] ...
